const $ = (id)=>document.getElementById(id);
const tabs=[['plan','Mein Plan'],['create','Eingabe'],['journal','Journal'],['challenge','Challenge']];
const markets=[
  {name:'Dow Jones Future',symbol:'YM=F',pointValue:5},
  {name:'Nasdaq 100 Future',symbol:'NQ=F',pointValue:20},
  {name:'S&P 500 Future',symbol:'ES=F',pointValue:50},
  {name:'Russell 2000 Future',symbol:'RTY=F',pointValue:50},
  {name:'DAX Future',symbol:'FDAX.DE',pointValue:25},
  {name:'Gold Future',symbol:'GC=F',pointValue:100},
  {name:'Silber Future',symbol:'SI=F',pointValue:5000},
  {name:'WTI Öl Future',symbol:'CL=F',pointValue:1000},
  {name:'Brent Öl Future',symbol:'BZ=F',pointValue:1000},
  {name:'Copper Future',symbol:'HG=F',pointValue:25000},
  {name:'US Dollar Index Future',symbol:'DX=F',pointValue:1000},
  {name:'Benutzerdefiniert',symbol:'CUSTOM',pointValue:1}
];
let uid=null, unsub=null, applyingRemote=false, saveTimer=null;
let state={
  plan:{market:'Dow Jones Future',symbol:'YM=F',direction:'Long',contracts:1,pointValue:5,entry:52900,target:54045,stop:52380,current:52988,zone:53500,why:'Laufende blaue Welle (v)\nEinstieg auf relevanten Fib-Niveau der Subwelle (ii)',rule:'Triff keine neue Entscheidung. Überprüfe zuerst deine ursprüngliche Entscheidung.',hkcm:'',tv:'',liveChange:null,lastLive:null},
  trades:[],
  challenge:Array(50).fill(null)
};

function fmt(n){return Number(n||0).toLocaleString('de-DE',{maximumFractionDigits:2})}
function pts(n){return (n>0?'+':'')+fmt(n)+'P'}
function num(v){return Number(v||0)}
function dist(a,b){return Math.round(Math.abs(num(a)-num(b))*100)/100}
function money(n){return Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0})}
function current(){return num(state.plan.current || state.plan.lastLive || state.plan.entry)}
function contracts(){return Number(String(state.plan.contracts||1).replace(',','.'))||1}
function pointValue(){return num(state.plan.pointValue || 1)}
function saveLocal(){localStorage.setItem('atlasStateV51',JSON.stringify(state))}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem('atlasStateV51')||'null');if(s)state={...state,...s,plan:{...state.plan,...s.plan},challenge:s.challenge||state.challenge,trades:s.trades||[]}}catch(e){}}
function queueSave(){saveLocal(); if(!uid||applyingRemote)return; clearTimeout(saveTimer); saveTimer=setTimeout(()=>{AtlasCloud.saveState(uid, cleanState()).then(()=>setCloud('Cloud gespeichert')).catch(e=>setCloud('Cloud Fehler: '+e.message));},500)}
function cleanState(){return {plan:state.plan,trades:state.trades,challenge:state.challenge}}
function setCloud(t){$('cloudStatus').textContent=t}

function makeNav(){const html=tabs.map((t,i)=>`<button data-tab="${t[0]}" class="${i?'':'active'}">${t[1]}</button>`).join('');$('nav').innerHTML=html;$('bottom').innerHTML=html;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));scrollTo(0,0)}

function fillMarkets(){ $('fMarketSelect').innerHTML=markets.map(m=>`<option value="${m.symbol}">${m.name}</option>`).join(''); $('fMarketSelect').onchange=()=>{const custom=$('fMarketSelect').value==='CUSTOM';$('fCustomMarket').classList.toggle('hidden',!custom);$('fCustomSymbol').classList.toggle('hidden',!custom);const m=markets.find(x=>x.symbol===$('fMarketSelect').value);if(m&&!custom)$('fPointValue').value=m.pointValue}; }

function imgHtml(src){return src?`<img src="${src}" class="open-img">`:`<div class="emptyShot">Noch kein Screenshot<br>über Eingabe hinzufügen</div>`}
function wireImages(){document.querySelectorAll('.open-img').forEach(img=>img.onclick=()=>{ $('modalImg').src=img.src; $('imgModal').classList.add('show'); });}
function loadImage(file,type){ if(!file)return; const r=new FileReader(); r.onload=()=>{state.plan[type]=r.result; queueSave(); loadForm(); render();}; r.readAsDataURL(file); }

function loadForm(){const p=state.plan; const known=markets.find(m=>m.symbol===p.symbol);$('fMarketSelect').value=known?p.symbol:'CUSTOM';$('fCustomMarket').classList.toggle('hidden',!!known);$('fCustomSymbol').classList.toggle('hidden',!!known);$('fCustomMarket').value=p.market||'';$('fCustomSymbol').value=p.symbol||'';$('fDirection').value=p.direction||'Long';$('fContracts').value=p.contracts||1;$('fPointValue').value=p.pointValue||1;$('fEntry').value=p.entry||'';$('fTarget').value=p.target||'';$('fStop').value=p.stop||'';$('fZone').value=p.zone||'';$('fWhy').value=p.why||'';$('fRule').value=p.rule||'';$('hkcmPreview').innerHTML=imgHtml(p.hkcm);$('tvPreview').innerHTML=imgHtml(p.tv);wireImages();}

function render(){const p=state.plan,c=current();$('marketTitle').textContent=`${p.market||'–'} · ${p.direction||'–'}`;$('directionLine').textContent=`${p.contracts||1} Kontrakt(e) · ${p.symbol||'–'}`;$('dEntry').textContent=fmt(p.entry);$('dTarget').textContent=fmt(p.target);$('dStop').textContent=fmt(p.stop);$('dCurrent').textContent=fmt(c);$('sStop').textContent=fmt(p.stop);$('sEntry').textContent=fmt(p.entry);$('sTarget').textContent=fmt(p.target);$('livePrice').textContent=p.lastLive?fmt(p.lastLive):'–';$('liveChange').textContent=p.liveChange==null?'–':pts(p.liveChange);$('liveStatus').textContent=p.lastLive?`Letzte Aktualisierung: ${p.lastLiveTime||'–'}`:'Live-Daten noch nicht aktualisiert.';$('whyList').innerHTML=(p.why||'').split('\n').filter(Boolean).map(x=>`<div class="pill">✓ ${x}</div>`).join('') || '<p>Noch keine Analyse hinterlegt.</p>';$('mentorQuote').textContent='„'+(p.rule||'Erst Plan prüfen, dann handeln.')+'“';$('pEntry').textContent=pts(dist(c,p.entry));$('pTarget').textContent=pts(dist(p.target,c));$('pStop').textContent=pts(dist(c,p.stop)); const riskPts=dist(p.entry,p.stop), chancePts=dist(p.target,p.entry), crv=riskPts?chancePts/riskPts:0;$('crv').textContent=crv?crv.toFixed(2):'–';$('riskMoney').textContent=money(riskPts*pointValue()*contracts());$('chanceMoney').textContent=money(chancePts*pointValue()*contracts()); const min=Math.min(num(p.stop),num(p.target)),max=Math.max(num(p.stop),num(p.target));$('bar').style.width=Math.max(0,Math.min(100,(c-min)/(max-min)*100))+'%';$('hkcmView').innerHTML=imgHtml(p.hkcm);$('tvView').innerHTML=imgHtml(p.tv);wireImages();brain();renderTrades();renderChallenge();}

function brain(){const p=state.plan,c=current(),long=p.direction==='Long';let phase='✓ PLAN LÄUFT',mood='Geduld',text='Der Markt bewegt sich innerhalb deines Plans.',decision='Keine spontane Entscheidung. Prüfe zuerst die ursprüngliche Analyse.',risk='green'; const near=(a,b,range)=>dist(a,b)<=range; const range=Math.max(10,dist(p.entry,p.stop)*0.15); if((long&&c<p.entry)||(!long&&c>p.entry)){phase='VOR EINSTIEG';mood='Warten';text='Nicht hinterherlaufen. Der Markt muss zu deinem geplanten Einstieg kommen.';decision='FOMO-Risiko: Kein Einstieg außerhalb deines Plans.';risk='green'} if((long&&c>=p.entry)||(!long&&c<=p.entry)){phase='✓ POSITION AKTIV';mood='Plan halten';text='Der Trade ist aktiv. Vermeide unnötige Eingriffe.';decision='Halte dich an Einstieg, Ziel, Stop und Mentorregel.';risk='green'} if(p.zone&&near(c,p.zone,range)){phase='PRÜFZONE';mood='Ruhig prüfen';text='Prüfzone erreicht. Erst Plan prüfen, dann handeln.';decision='Atlas blendet deine ursprüngliche Analyse ein. Entscheide objektiv.';risk='orange'} if(near(c,p.stop,range)){phase='STOP-NÄHE';mood='Keine Angstentscheidung';text='Der Markt nähert sich dem Stop. Prüfe ausschließlich deine Invalidierungsregel.';decision='Nicht aus Angst schließen und keinen Stop verschieben.';risk='red'} if(near(c,p.target,range)){phase='ZIELBEREICH';mood='Keine Euphorie';text='Zielbereich erreicht. Folge deinem Ausstiegsplan.';decision='Nicht gierig werden. Plane den Ausstieg nach deiner Regel.';risk='orange'} $('phaseText').textContent=phase;$('brainMood').textContent=mood;$('brainText').textContent=text;$('brainHeadline').textContent=mood;$('decisionTitle').textContent=phase;$('decisionText').textContent=decision;$('riskDot').className='risk-dot '+(risk==='red'?'red':risk==='orange'?'orange':'');}

function savePlan(){const sym=$('fMarketSelect').value;const marketObj=markets.find(m=>m.symbol===sym);const custom=sym==='CUSTOM';state.plan={...state.plan,market:custom?$('fCustomMarket').value:marketObj.name,symbol:custom?$('fCustomSymbol').value:marketObj.symbol,direction:$('fDirection').value,contracts:$('fContracts').value||1,pointValue:num($('fPointValue').value)||1,entry:num($('fEntry').value),target:num($('fTarget').value),stop:num($('fStop').value),zone:num($('fZone').value),why:$('fWhy').value,rule:$('fRule').value}; if(!state.plan.entry||!state.plan.target||!state.plan.stop){$('saveMsg').textContent='Bitte Einstieg, Ziel und Stop ausfüllen.';return;} $('saveMsg').textContent='Plan gespeichert und Cloud-Sync gestartet.'; queueSave(); fetchYahoo(); render(); show('plan');}

async function fetchYahoo(){const p=state.plan;if(!p.symbol)return; $('liveStatus').textContent='Yahoo-Daten werden geladen…'; const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(p.symbol)}?range=1d&interval=1m`; const proxies=[`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,`https://corsproxy.io/?${encodeURIComponent(url)}`]; for(const proxy of proxies){try{const res=await fetch(proxy); if(!res.ok)throw new Error('HTTP '+res.status); const data=await res.json(); const r=data.chart.result?.[0]; const meta=r?.meta; const price=meta?.regularMarketPrice || meta?.previousClose; if(price){const old=state.plan.current||price; state.plan.current=price; state.plan.lastLive=price; state.plan.liveChange=price-old; state.plan.lastLiveTime=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}); queueSave(); render(); return;}}catch(e){console.warn(e)}} $('liveStatus').textContent='Yahoo konnte nicht geladen werden. Prüfe Symbol oder später erneut versuchen.';}

function closeTrade(){const r=num($('closeResult').value); if(!r){alert('Bitte Ergebnis in Punkten eintragen.');return} const p=state.plan; state.trades.unshift({id:Date.now(),date:new Date().toLocaleString('de-DE'),market:p.market,direction:p.direction,result:r,note:$('closeNote').value||'',symbol:p.symbol}); $('closeResult').value='';$('closeNote').value=''; queueSave(); renderTrades(); show('journal');}
function renderTrades(){const list=$('tradeList'); if(!state.trades.length){list.innerHTML='<p>Noch keine beendeten Trades.</p>';return} list.innerHTML=state.trades.map(t=>`<div class="tradeRow"><div><b>${t.date} · ${t.market}</b><br><span>${t.direction} · ${t.note||''}</span></div><div>${t.result>=0?'Gewinn':'Verlust'}</div><div class="${t.result>=0?'plus':'minus'}">${pts(t.result)}</div><button class="ghost" data-del="${t.id}">×</button></div>`).join(''); document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.trades=state.trades.filter(t=>String(t.id)!==String(b.dataset.del));queueSave();renderTrades();});}
function exportJournal(){const text=state.trades.map(t=>`${t.date}; ${t.market}; ${t.direction}; ${t.result} Punkte; ${t.note||''}`).join('\n'); const blob=new Blob([`Atlas Journal\n\n${text}`],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='atlas-journal.txt'; a.click();}
function toggleBox(i){state.challenge[i]=state.challenge[i]?null:new Date().toLocaleString('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'});queueSave();renderChallenge()}
function renderChallenge(){const done=state.challenge.filter(Boolean).length;$('wealthNow').textContent=done+' / 50';$('wealthPct').textContent=Math.round(done/50*100)+'%';$('lastCheck').textContent=state.challenge.filter(Boolean).slice(-1)[0]||'–';$('boxes').innerHTML=Array.from({length:50},(_,i)=>`<div class="box ${state.challenge[i]?'done':''}" data-box="${i}">${i+1}<br>${state.challenge[i]||''}</div>`).join('');document.querySelectorAll('[data-box]').forEach(b=>b.onclick=()=>toggleBox(Number(b.dataset.box)));}

function wire(){makeNav();fillMarkets();$('loginBtn').onclick=()=>AtlasCloud.login($('authEmail').value,$('authPassword').value).catch(e=>$('authMsg').textContent=e.message);$('registerBtn').onclick=()=>AtlasCloud.register($('authEmail').value,$('authPassword').value).catch(e=>$('authMsg').textContent=e.message);$('logoutBtn').onclick=()=>AtlasCloud.logout();$('savePlanBtn').onclick=savePlan;$('refreshYahooBtn').onclick=fetchYahoo;$('closeTradeBtn').onclick=closeTrade;$('exportJournalBtn').onclick=exportJournal;$('hkcmFile').onchange=e=>loadImage(e.target.files[0],'hkcm');$('tvFile').onchange=e=>loadImage(e.target.files[0],'tv');$('modalClose').onclick=()=>$('imgModal').classList.remove('show');$('imgModal').onclick=e=>{if(e.target.id==='imgModal')$('imgModal').classList.remove('show')};}

function startCloud(){AtlasCloud.onAuth(user=>{if(unsub){unsub();unsub=null} if(!user){uid=null;$('authScreen').classList.remove('hidden');$('app').classList.add('hidden');return} uid=user.uid;$('authScreen').classList.add('hidden');$('app').classList.remove('hidden');setCloud('Cloud verbunden: '+user.email);unsub=AtlasCloud.watchState(uid,remote=>{if(remote){applyingRemote=true;state={...state,...remote,plan:{...state.plan,...remote.plan},trades:remote.trades||[],challenge:remote.challenge||Array(50).fill(null)};saveLocal();loadForm();render();applyingRemote=false;setCloud('Cloud synchronisiert')}else{queueSave();}});});}

loadLocal();wire();loadForm();render();startCloud();setInterval(()=>{if(uid&&state.plan.symbol)fetchYahoo()},60000);
