const markets=[
 {name:'Dow Jones Future',symbol:'YM=F',pointValue:5,group:'US'},
 {name:'Nasdaq 100 Future',symbol:'NQ=F',pointValue:20,group:'US'},
 {name:'S&P 500 Future',symbol:'ES=F',pointValue:50,group:'US'},
 {name:'Russell 2000 Future',symbol:'RTY=F',pointValue:50,group:'US'},
 {name:'DAX Future',symbol:'FDAX.DE',pointValue:25,group:'EU'},
 {name:'Gold Future',symbol:'GC=F',pointValue:100,group:'Metalle'},
 {name:'Silber Future',symbol:'SI=F',pointValue:5000,group:'Metalle'},
 {name:'Copper Future',symbol:'HG=F',pointValue:25000,group:'Metalle'},
 {name:'WTI Öl Future',symbol:'CL=F',pointValue:1000,group:'Rohstoffe'},
 {name:'Brent Öl Future',symbol:'BZ=F',pointValue:1000,group:'Rohstoffe'},
 {name:'US Dollar Index Future',symbol:'DX=F',pointValue:1000,group:'FX'},
 {name:'10Y Treasury Note Future',symbol:'ZN=F',pointValue:1000,group:'Bonds'},
 {name:'Benutzerdefiniert',symbol:'',pointValue:1,group:'Custom'}
];
const $=id=>document.getElementById(id);
const state={plan:JSON.parse(localStorage.getItem('atlas.plan')||'null'),journal:JSON.parse(localStorage.getItem('atlas.journal')||'[]'),challenge:JSON.parse(localStorage.getItem('atlas.challenge')||'[]')};
function fmt(n,d=2){if(n===null||n===undefined||Number.isNaN(Number(n)))return'–';return Number(n).toLocaleString('de-DE',{maximumFractionDigits:d})}
function money(n){return fmt(n,0)+' €'}
function setLiveStatus(text,cls=''){if(typeof liveStatus!=='undefined'&&liveStatus){liveStatus.textContent=text;liveStatus.className='live-status '+cls}}
function points(n){if(n===null||n===undefined||Number.isNaN(Number(n)))return'–';return (n>=0?'+':'')+fmt(n,2)+' P'}
function save(){localStorage.setItem('atlas.plan',JSON.stringify(state.plan));localStorage.setItem('atlas.journal',JSON.stringify(state.journal));localStorage.setItem('atlas.challenge',JSON.stringify(state.challenge))}
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));$('headline').textContent={dashboard:'Dashboard',create:'Eingabe',plan:'Mein Plan',journal:'Journal',challenge:'Challenge'}[id]||'Atlas';window.scrollTo(0,0)}
function initNav(){document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.go)))}
function initMarkets(){marketSelect.innerHTML=markets.map((m,i)=>`<option value="${i}">${m.name}</option>`).join('');marketSelect.addEventListener('change',()=>{const m=markets[marketSelect.value];symbolInput.value=m.symbol;pointValueInput.value=m.pointValue||1})}
function validatePlan(p){const e=Number(p.entry),s=Number(p.stop),t=Number(p.target);const errors=[];if(!p.market)errors.push('Markt fehlt.');if(!p.direction)errors.push('Richtung fehlt.');if(!e||!s||!t)errors.push('Einstieg, Stop und Ziel müssen ausgefüllt sein.');if(p.direction==='Long'&&s>=e)errors.push('Long: Stop muss unter dem Einstieg liegen.');if(p.direction==='Long'&&t<=e)errors.push('Long: Ziel muss über dem Einstieg liegen.');if(p.direction==='Short'&&s<=e)errors.push('Short: Stop muss über dem Einstieg liegen.');if(p.direction==='Short'&&t>=e)errors.push('Short: Ziel muss unter dem Einstieg liegen.');const risk=Math.abs(e-s),chance=Math.abs(t-e);if(risk&&chance&&chance/risk<1)errors.push('CRV liegt unter 1,0. Trade bewusst prüfen.');return errors}
function readImage(input){return new Promise(resolve=>{const file=input.files&&input.files[0];if(!file)return resolve('');const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)})}
async function savePlan(){const m=markets[marketSelect.value];const previousCurrent=Number(state.plan?.current);const entryValue=Number(entryInput.value);const p={market:m.name==='Benutzerdefiniert'?(symbolInput.value||'Custom'):m.name,symbol:symbolInput.value.trim(),direction:directionInput.value,contracts:contractsInput.value||'1',entry:+entryInput.value,stop:+stopInput.value,target:+targetInput.value,zone:+zoneInput.value,current:Number.isFinite(previousCurrent)?previousCurrent:entryValue,pointValue:+pointValueInput.value||1,why:whyInput.value,rule:ruleInput.value,hkcm:await readImage(hkcmInput)||state.plan?.hkcm||'',tv:await readImage(tvInput)||state.plan?.tv||'',createdAt:new Date().toISOString()};const errors=validatePlan(p);validationBox.innerHTML=errors.length?'⚠️ '+errors.join('<br>'):'✓ Plan plausibel. Live-Kurs wird geladen.';if(errors.some(e=>!e.includes('CRV')))return;state.plan=p;save();renderAll();screen('plan');fetchYahoo(true)}
function loadPlanToForm(){if(!state.plan){marketSelect.value=1;marketSelect.dispatchEvent(new Event('change'));return}const idx=markets.findIndex(m=>m.symbol===state.plan.symbol);marketSelect.value=idx>=0?idx:markets.length-1;symbolInput.value=state.plan.symbol||'';directionInput.value=state.plan.direction||'Long';contractsInput.value=state.plan.contracts||'';entryInput.value=state.plan.entry||'';stopInput.value=state.plan.stop||'';targetInput.value=state.plan.target||'';zoneInput.value=state.plan.zone||'';pointValueInput.value=state.plan.pointValue||1;whyInput.value=state.plan.why||'';ruleInput.value=state.plan.rule||'';renderPreview(hkcmPreview,state.plan.hkcm);renderPreview(tvPreview,state.plan.tv)}
function calc(p){if(!p)return null;const current=Number(p.current),entry=Number(p.entry),stop=Number(p.stop),target=Number(p.target),zone=Number(p.zone||entry),pv=Number(p.pointValue||1),contracts=parseFloat(String(p.contracts).replace(',','.'))||1;const riskPts=Math.abs(entry-stop),chancePts=Math.abs(target-entry);const crv=riskPts?chancePts/riskPts:null;const long=p.direction==='Long';const toEntry=Math.abs(current-entry),toStop=Math.abs(current-stop),toTarget=Math.abs(target-current),toZone=Math.abs(zone-current);const riskMoney=riskPts*pv*contracts,chanceMoney=chancePts*pv*contracts;let progress=long?(current-stop)/(target-stop):(stop-current)/(stop-target);progress=Math.max(0,Math.min(1,progress));return{current,entry,stop,target,zone,pv,contracts,riskPts,chancePts,crv,toEntry,toStop,toTarget,toZone,riskMoney,chanceMoney,progress,long}}
function brain(p){const c=calc(p);if(!p||!c)return{title:'Warte auf Plan',msg:'Lege zuerst einen Trade an.',risk:'Neutral',cls:''};const active=c.long?c.current>=c.entry:c.current<=c.entry;const stopped=c.long?c.current<=c.stop:c.current>=c.stop;const targetHit=c.long?c.current>=c.target:c.current<=c.target;const nearStop=c.toStop<=c.riskPts*0.18;const nearTarget=c.toTarget<=c.chancePts*0.15;const nearZone=c.toZone<=Math.max(c.riskPts*0.15,20);if(stopped)return{title:'Invalidierung erreicht',msg:'Nicht diskutieren. Prüfe nur, ob dein dokumentierter Stop/Invalidierungspunkt ausgelöst wurde. Wenn ja: Trade beenden und ins Journal.',risk:'Rot',cls:'risk-red'};if(targetHit)return{title:'Zielbereich erreicht',msg:'Der Trade hat geliefert. Handle jetzt nach deinem Ausstiegsplan, nicht aus Euphorie.',risk:'Grün',cls:'risk-green'};if(!active)return{title:'Vor Einstieg',msg:'Nicht hinterherlaufen. Dein Job ist Geduld: Einstieg abwarten oder Setup verwerfen, aber nicht spontan jagen.',risk:'Gelb',cls:'risk-yellow'};if(nearStop)return{title:'Stop-Zone',msg:'Angst ist jetzt normal. Keine neue Entscheidung aus Emotion. Nur die ursprüngliche Invalidierung zählt.',risk:'Rot',cls:'risk-red'};if(nearTarget)return{title:'Nahe Zielzone',msg:'Nicht zu früh aussteigen. Wenn Teilgewinn geplant war, dann planmäßig. Wenn nicht: Ziel respektieren.',risk:'Grün',cls:'risk-green'};if(nearZone)return{title:'Prüfzone',msg:'Analyse einblenden, Struktur prüfen, aber keine spontane Entscheidung treffen. Erst ursprüngliche Regel lesen.',risk:'Gelb',cls:'risk-yellow'};return{title:'Plan läuft',msg:'Der Trade bewegt sich innerhalb deines Plans. Nicht eingreifen, solange keine objektive Strukturänderung vorliegt.',risk:'Grün',cls:'risk-green'}}
async function fetchYahoo(force=false){if(!state.plan?.symbol){setLiveStatus('Kein Symbol hinterlegt','');return;}setLiveStatus('Live-Kurs wird geladen…','risk-yellow');const yahooUrl=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(state.plan.symbol)}?interval=1m&range=1d`;const urls=[yahooUrl,`https://api.allorigins.win/raw?url=${encodeURIComponent(yahooUrl)}`];let lastError=null;for(const url of urls){try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();const r=data.chart?.result?.[0];const price=r?.meta?.regularMarketPrice ?? r?.meta?.previousClose;const ts=r?.meta?.regularMarketTime;if(price){state.plan.current=Number(price);state.plan.lastPriceAt=ts?new Date(ts*1000).toISOString():new Date().toISOString();save();renderAll();setLiveStatus(`Live: ${fmt(price)} · ${new Date(state.plan.lastPriceAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`,'risk-green');return true;}}catch(e){lastError=e;}}console.warn('Yahoo Abruf nicht möglich.',lastError);setLiveStatus('Live-Daten nicht erreichbar · letzter Kurs bleibt aktiv','risk-red');return false;}
function renderPreview(el,src){el.innerHTML=src?`<img src="${src}" alt="Screenshot">`:'Noch kein Bild';if(src)el.querySelector('img').onclick=()=>openImage(src)}
function renderPlan(){const p=state.plan,c=calc(p),b=brain(p);dashTitle.textContent=p?`${p.market} · ${p.direction}`:'Noch kein aktiver Trade';dashText.textContent=p?`Symbol ${p.symbol||'–'} · ${p.contracts||'–'} · Atlas überwacht deine Tradephase.`:'Lege unter „Eingabe“ deinen nächsten Trade an.';brainTitle.textContent=b.title;brainMessage.textContent=b.msg;riskPill.textContent='';riskPill.setAttribute('aria-label',b.risk);riskPill.className='risk-pill '+b.cls;statMarket.textContent=p?p.market:'–';statPrice.textContent=c?fmt(c.current):'–';statCrv.textContent=c?.crv?fmt(c.crv,2):'–';planTitle.textContent=p?`${p.market} · ${p.direction}`:'Kein aktiver Trade';phaseText.textContent=b.title;planBrainTitle.textContent=b.title;planBrainMessage.textContent=b.msg;progressBar.style.width=c?(c.progress*100)+'%':'0%';if(c){mCurrent.textContent=fmt(c.current);mEntry.textContent=fmt(c.entry);mStop.textContent=fmt(c.stop);mTarget.textContent=fmt(c.target);mToEntry.textContent=points(c.toEntry);mToStop.textContent=points(c.toStop);mToTarget.textContent=points(c.toTarget);mCrv.textContent=fmt(c.crv,2);mRiskMoney.textContent=money(c.riskMoney);mChanceMoney.textContent=money(c.chanceMoney)}else document.querySelectorAll('.metrics b').forEach(x=>x.textContent='–');whyList.innerHTML=p?.why?p.why.split('\n').filter(Boolean).map(x=>`<div class="pill">✓ ${x}</div>`).join(''):'–';mentorRule.textContent=p?.rule||'–';renderPreview(hkcmPlan,p?.hkcm);renderPreview(tvPlan,p?.tv)}
function closeTrade(){if(!state.plan)return alert('Kein aktiver Trade vorhanden.');const c=calc(state.plan);const resultPts=state.plan.direction==='Long'?c.current-c.entry:c.entry-c.current;state.journal.unshift({...state.plan,closedAt:new Date().toISOString(),resultPts,resultMoney:resultPts*c.pv*c.contracts});state.plan=null;save();renderAll();screen('journal')}
function renderJournal(){journalList.innerHTML=state.journal.length?state.journal.map((t,i)=>`<div class="journal-item"><div><b>${new Date(t.closedAt).toLocaleDateString('de-DE')} · ${t.market}</b><br><span>${t.direction} · ${t.symbol||''}</span><br><span class="${t.resultPts>=0?'gain':'loss'}">${points(t.resultPts)} · ${money(t.resultMoney)}</span></div><button onclick="deleteJournal(${i})">Löschen</button></div>`).join(''):'Noch keine beendeten Trades.'}
window.deleteJournal=i=>{state.journal.splice(i,1);save();renderJournal()}
function exportJournal(){const w=window.open('','_blank');w.document.write(`<h1>Atlas Journal</h1>${state.journal.map(t=>`<p><b>${new Date(t.closedAt).toLocaleDateString('de-DE')} · ${t.market}</b><br>${t.direction} · Ergebnis: ${points(t.resultPts)} · ${money(t.resultMoney)}<br>${(t.why||'').replaceAll('\n','<br>')}</p><hr>`).join('')}`);w.document.close();w.print()}
function renderChallenge(){const done=state.challenge.filter(Boolean).length;challengeDone.textContent=done+' / 50';challengeMoney.textContent=money(done*20000);challengeLast.textContent=state.challenge.filter(Boolean).slice(-1)[0]||'–';challengeGrid.innerHTML=Array.from({length:50},(_,i)=>`<div class="challenge-box ${state.challenge[i]?'done':''}" onclick="toggleChallenge(${i})">${i+1}<br>${state.challenge[i]||''}</div>`).join('')}
window.toggleChallenge=i=>{state.challenge[i]=state.challenge[i]?null:new Date().toLocaleString('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'});save();renderChallenge()}
function openImage(src){imageModal.querySelector('img').src=src;imageModal.classList.add('show')}imageModal.addEventListener('click',()=>imageModal.classList.remove('show'));
function marketClock(){const now=new Date();const de=now.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});const day=now.getDay();const min=now.getHours()*60+now.getMinutes();const open=day>=1&&day<=5&&min>=15*60+30&&min<22*60;marketStatus.textContent=`${de} · US Future/Session ${open?'geöffnet':'geschlossen'}`;marketStatus.className='market-status '+(open?'risk-green':'risk-yellow')}
function renderAll(){renderPlan();renderJournal();renderChallenge()}
function init(){initNav();initMarkets();loadPlanToForm();savePlanBtn.onclick=savePlan;closeTradeBtn.onclick=closeTrade;exportBtn.onclick=exportJournal;hkcmInput.onchange=async()=>renderPreview(hkcmPreview,await readImage(hkcmInput));tvInput.onchange=async()=>renderPreview(tvPreview,await readImage(tvInput));marketClock();setInterval(marketClock,30000);renderAll();fetchYahoo(true);setInterval(fetchYahoo,60000)}
init();
